## Ingress NGINX Helm Chart Values
## 
## 기본 values를 가져오려면 다음 명령어를 실행하세요:
##   helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
##   helm repo update
##   helm show values ingress-nginx/ingress-nginx > values.yaml
##
## 실제 적용된 설정을 확인하려면:
##   helm get values ingress-nginx -n default

controller:
  name: controller

  ingressClassResource:
    name: nginx
    enabled: true
    controllerValue: "k8s.io/ingress-nginx"

  service:
    externalTrafficPolicy: "Local"
    type: LoadBalancer
    loadBalancerSourceRanges: []

  config:
    enable-real-ip: "true"
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    forwarded-for-header: "X-Forwarded-For"
    ssl-redirect: "false"
    log-format-upstream: >-
      {"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr",
      "x_forward_for": "$http_x_forwarded_for", "full_x_forward_for": "$full_x_forwarded_for",
      "request_id": "$req_id", "remote_user":
      "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time,
      "status": $status, "vhost": "$host", "request_proto": "$server_protocol",
      "path": "$uri", "request_query": "$args", "request_length": $request_length,
      "duration": $request_time,"method": "$request_method", "http_referrer":
      "$http_referer", "http_user_agent": "$http_user_agent" }
